drop table if exists account cascade;
drop table if exists card cascade;
drop table if exists payment_method cascade;
create table account (
                         id bigint auto_increment primary key,
                         account_num varchar(255),
                         account_password varchar(255),
                         account_holder varchar(255),
                         account_holder_info varchar(255),
                         bank_name varchar(255),
                         is_verified boolean not null,
                         create_dtm timestamp(6) not null,
                         modify_dtm timestamp(6) not null
);
create table card (
                      id bigint auto_increment primary key,
                      cvc integer not null,
                      bank_name varchar(255),
                      card_num varchar(255),
                      card_password varchar(255),
                      expiration_date varchar(255),
                      is_verified boolean not null,
                      create_dtm timestamp(6) not null,
                      modify_dtm timestamp(6) not null
);
create table member (
                        id BIGINT generated by default as identity,
                        name varchar(255),
                        primary key (id)
);
create table payment_method (
                                id bigint auto_increment primary key,
                                account_id bigint,
                                card_id bigint,
                                member_id bigint not null,
                                payment_method_type varchar(255) check (payment_method_type in ('CARD','ACCOUNT')),
                                is_default boolean not null,
                                create_dtm timestamp(6) not null,
                                modify_dtm timestamp(6) not null
);

ALTER TABLE payment_method
    ADD CONSTRAINT FK_PAYMENT_ACCOUNT
        FOREIGN KEY(account_id)
    references account(id);

ALTER TABLE payment_method
    ADD CONSTRAINT FK_PAYMENT_CARD
        FOREIGN KEY (card_id)
    references card(id);

ALTER TABLE payment_method
    ADD CONSTRAINT FK_PAYMENT_MEMBER
        FOREIGN KEY (member_id)
    references member(id);